### PR TITLE
cut: refresh page: fix existing example and add a new one

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**

### CODE REVIEW

**Comment by EmilySeville7cfg** [comment]
@chrisallenlane, what do you think about `(-d #|--delimiter #)` syntax to present both short and long options at once?

**Comment by chrisallenlane** [comment]
@EmilySeville7cfg, I would prefer to avoid that. Doing that just adds noise, IMO. I'd like to keep the examples relatively terse.

**Comment by EmilySeville7cfg** [comment]
Fixed. :)

**Comment by EmilyGraceSeville7cf** [comment]
I am closing this PR to make project maintainer pay attention for it.

**Pull request closed without merging**
