### PR TITLE
apt: refresh page

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
- add missing colons to the end of comments

### CODE REVIEW

**Comment by chrisallenlane** [comment]
Thanks. Merging.

@EmilySeville7cfg, a request: for simple edits like these, do you think you could just batch them into a larger PR?

This kind of work is valuable, but very numerous, small PRs has an effect something akin to a denial-of-service attack on my Github notifications.

Going to be honest with you: when I log into Github and see 50+ notifications, I usually just conclude that I don't feel like dealing with this on my weekend (or evening, or whatever), and I just close the tab.

If we could batch these in less frequent, larger PRs, that would remove a significant source of friction in me addressing them.

**Comment by EmilyGraceSeville7cf** [comment]
> do you think you could just batch them into a larger PR?

Sure, noted. Thanks for a response. 😄 

> Going to be honest with you: when I log into Github and see 50+ notifications, I usually just conclude that I don't feel like dealing with this on my weekend (or evening, or whatever), and I just close the tab.

It's literally describes me when I don't open GitHub for a few days.

**Comment by chrisallenlane** [comment]
Great. Thanks :)

**Review by Grimez99 — COMMENTED** [review]
-#

**Pull request merged**
