### PR TITLE
Standardize file/directory placeholders

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**
Use `"<path/to/file>"` and `"<path/to/directory>"` instead of not standardized variations like `<file>`, `<dir>` and `<directory>`.

Users should have the same the best experience on all pages.

### CODE REVIEW

**Comment by chrisallenlane** [comment]
@EmilySeville7cfg, I would actually rather avoid using `<path/to/file>`.

In docopt, the placeholders (like `<foo>`) are names, so it's not correct to put paths here.

Alternatively, something like `<infile>`, `<outfile>`, `<file-1>`, `<file-2>`, etc, might make sense, because those are descriptive.

Please let me know if this makes sense. Thanks.

**Comment by EmilyGraceSeville7cf** [comment]
Yeah, such way of presenting paths makes sense. I've updated #194 PR according to your comment. :)

**Comment by edgester** [comment]
@chrisallenlane , How do we resolve issue #190? What is the preferred way to do placeholders for the most common ones? For example, when the find command, would we use `find <directory> ...` or something else. I'm just looking to be consistent. I like what @EmilySeville7cfg  is doing with cleaning up.

**Comment by EmilyGraceSeville7cf** [comment]
@edgester, I've proposed [these](https://github.com/cheat/cheatsheets/pull/194/files#diff-438478e7713ffdb96be895cd2cba03144f30c04f1442ae246acdeb2f1c13efd5R41) rules for placeholders:

>   - For path placeholders use `<in-file>`, `<out-file>`, or `<file>`. Almost the same applies to directories
>    but instead of term `file` `dir` term is used.

Initially I've tried to apply TlDr page placeholder syntax here but this idea was declined so I've suggested alternatives. ;)

**Comment by EmilyGraceSeville7cf** [comment]
I am closing this PR to make project maintainer pay attention for it.

**Pull request closed without merging**
